services:
  db:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - my_network

  url-shortener-app:
    image: url-shortener:latest
    container_name: url-shortener-container
    depends_on:
      - db
    command: ["./scripts/wait-for-it.sh", "db:3306", "timeout=30", "java", "-jar", "/app/urlShorter-1.0-SNAPSHOT.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/mydb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: rootpassword
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SPRING_JPA_SHOW_SQL: "true"
    ports:
      - "8989:8989"
    networks:
      - my_network

networks:
  my_network:
    driver: bridge

volumes:
  mysql_data: